site_name: AWS PDK
site_description: Prototype Development Kit (PDK).
repo_name: aws/pdk
repo_url: https://github.com/aws/pdk
site_url: https://aws.github.io/pdk/
copyright: Copyright &copy; 2022 Amazon Web Services, Inc.

docs_dir: content
extra_css:
  - assets/stylesheets/amazon-ember-display.css
  - assets/stylesheets/extra.css

nav:
  - ...

extra:
  social:
    - icon: fontawesome/brands/aws
      name: Amazon Web Services, Inc.
      link: https://aws.amazon.com

theme:
  name: material
  font: false
  logo: assets/images/logo.png
  icon:
    logo: fontawesome/brands/aws
    repo: fontawesome/brands/github
  favicon: assets/images/favicon.png
  palette:
    scheme: default
  features:
    - toc.follow
    - navigation.indexes
    - navigation.instant
    - navigation.tabs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      repo_url_shortener: true
      provider: github
      user: aws
      repo: pdk
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - awesome-pages:
      filename: .pages.yml
  - git-revision-date
  - search
